# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# ID3 tag music genres are surprisingly specific.

Genre.destroy_all
Artist.destroy_all
Song.destroy_all
Note.destroy_all

genres = Hash[[
  "Blues",
  "Classic Rock",
  "Country",
  "Dance",
  "Disco",
  "Funk",
  "Grunge",
  "Hip-Hop",
  "Jazz",
  "Metal",
  "New Age",
  "Oldies",
  "Other",
  "Pop",
  "R&B",
  "Rap",
  "Reggae",
  "Rock",
  "Techno",
  "Industrial",
  "Alternative",
  "Ska",
  "Death Metal",
  "Pranks",
  "Soundtrack",
  "Euro-Techno",
  "Ambient",
  "Trip-Hop",
  "Vocal",
  "Jazz+Funk",
  "Fusion",
  "Trance",
  "Classical",
  "Instrumental",
  "Acid",
  "House",
  "Game",
  "Sound Clip",
  "Gospel",
  "Noise",
  "Alternative Rock",
  "Bass",
  "Soul",
  "Punk",
  "Space",
  "Meditative",
  "Instrumental Pop",
  "Instrumental Rock",
  "Ethnic",
  "Gothic",
  "Darkwave",
  "Techno-Industrial",
  "Electronic",
  "Pop-Folk",
  "Eurodance",
  "Dream",
  "Southern Rock",
  "Comedy",
  "Cult",
  "Gangsta",
  "Top 40",
  "Christian Rap",
  "Pop/Funk",
  "Jungle",
  "Native US",
  "Cabaret",
  "New Wave",
  "Psychadelic",
  "Rave",
  "Showtunes",
  "Trailer",
  "Lo-Fi",
  "Tribal",
  "Acid Punk",
  "Acid Jazz",
  "Polka",
  "Retro",
  "Musical",
  "Rock & Roll",
  "Hard Rock",
  "Folk",
  "Folk-Rock",
  "National Folk",
  "Swing",
  "Fast Fusion",
  "Bebob",
  "Latin",
  "Revival",
  "Celtic",
  "Bluegrass",
  "Avantgarde",
  "Gothic Rock",
  "Progressive Rock",
  "Psychedelic Rock",
  "Symphonic Rock",
  "Slow Rock",
  "Big Band",
  "Chorus",
  "Easy Listening",
  "Acoustic",
  "Humour",
  "Speech",
  "Chanson",
  "Opera",
  "Chamber Music",
  "Sonata",
  "Symphony",
  "Booty Bass",
  "Primus",
  "Porn Groove",
  "Satire",
  "Slow Jam",
  "Club",
  "Tango",
  "Samba",
  "Folklore",
  "Ballad",
  "Power Ballad",
  "Rhythmic Soul",
  "Freestyle",
  "Duet",
  "Punk Rock",
  "Drum Solo",
  "Acapella",
  "Euro-House",
  "Dance Hall",
  "Goa",
  "Drum & Bass",
  "Club - House",
  "Hardcore",
  "Terror",
  "Indie",
  "BritPop",
  "Negerpunk",
  "Polsk Punk",
  "Beat",
  "Christian Gangsta Rap",
  "Heavy Metal",
  "Black Metal",
  "Crossover",
  "Contemporary Christian",
  "Christian Rock",
  "Merengue",
  "Salsa",
  "Thrash Metal",
  "Anime",
  "JPop",
  "Synthpop"
].map { |genre| [genre, Genre.find_or_create_by(name: genre)] }]


artists = Hash[[
  "Barry Gibb",
  "Eminem",
  "Alan Jackson",
  "Bon Iver",
  "Foo Fighters",
  "The Band Perry",
  "Harry Styles",
  "Gorillaz",
  "Enya",
  "Tyler",
  "Staind",
  "Post Malone",
  "Original Broadway Cast of Hamilton",
  "Talking Heads",
  "Creed",
  "Taylor Swift",
  "The Beatles",
  "Leon Bridges",
  "Michael Jackson"
].map { |artist| [artist, Artist.find_or_create_by(name: artist)]}]

songs = Hash[[
  "Late Land",
  "A Single Gift",
  "Cold Rhythm",
  "better Half House",
  "Still Need Midnight",
  "Lost People",
  "Pink Relationship",
  "True Love Knows No Sounds",
  "Calming Stranger",
  "Bass Midnight Stroll",
  "Unlikely Hours",
  "Club Night",
  "Blue Overture",
  "Chopin Mind",
  "Unspeakable Amazement",
  "Acid Girl",
  "Higher Morning Sun",
  "Southern Promises",
  "Rhythm Of Twilight"
].map{ |song| [song, Song.find_or_create_by(title: song)]}]

notes = Hash[[
  "Lorem ipsum dolor sit amet.",
  "consectetur adipiscing elit",
  "eiusmod tempor incididunt ut",
  "Tincidunt praesent semper feugiat",
  "Mauris pellentesque pulvinar pellentesque",
  "Vel pharetra vel turpis",
  "Suscipit adipiscing bibendum",
  "Scelerisque eu ultrices"
].map{ |note| [note, Note.find_or_create_by(content: note)]}]

